---
sudo: required
dist: trusty

# Test on PHP7
language: php
php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

# Cache composer dependencies
cache:
  directories:
    - vendor

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then chmod a+x tests/.travis/install_dependencies.sh; bash tests/.travis/install_dependencies.sh; pecl install libsodium-2.0.12; fi
  - phpenv config-rm xdebug.ini || true
  - php -m

install:
  - composer install -ovn

script:
  - ./vendor/bin/phpunit
